# Generated by Django 5.2.17 on 2026-10-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_min_duration', models.DurationField()),
                ('booking_max_duration', models.DurationField()),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='resource_capacity_gte_1'), models.CheckConstraint(condition=models.Q(('booking_max_duration__gte', models.F('booking_min_duration'))), name='resource_max_duration_gte_min'), models.CheckConstraint(condition=models.Q(('available_to__gt', models.F('available_from'))), name='resource_available_to_gt_from')],
            },
        ),
    ]
