# Generated by Django 5.2.17 on 2026-10-06 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_at', '-created_at'),
                'indexes': [models.Index(fields=['start_at'], name='booking_start_idx'), models.Index(fields=['end_at'], name='booking_end_idx'), models.Index(fields=['status'], name='booking_status_idx'), models.Index(fields=['resource', 'start_at', 'end_at'], name='booking_resource_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='booking_end_at_gt_start_at')],
            },
        ),
    ]
